# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92b538e43b657069b7d037e867949a7c89a3b8db227db5605c7c55164ef0efd3d3d4cf18e6e50f1ac7e5758b18159af92fcfbc097e1c92d67736085126008d6

test:
  secret_key_base: ebf7f7fdbeef1e9e6c3f41e20adf2bc3878032e68346a5130346afaaeb1e704a2cb94cb46f5e1b355ae9824a107a18344ff0f8c8eecca9851d9720d234491459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
